dateModified: 1596446368
email:
  fromEmail: $SITE_EMAIL
  fromName: $SITE_NAME
  replyToEmail: null
  template: null
  transportSettings:
    command: ''
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  2f26868b-418e-44a0-8e53-d367d9a163eb:
    name: 'Meta & Social Data'
  a6548a8e-edd2-4cbb-9200-db7de2726f75:
    name: Common
fields:
  1b7a3230-f24a-4ac2-a997-3289e43ddf25:
    contentColumnType: text
    fieldGroup: a6548a8e-edd2-4cbb-9200-db7de2726f75
    handle: cookieConsent
    instructions: ''
    name: 'Cookie Consent'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: 'Text Full.json'
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  90552b17-3ba7-452a-9dfd-0b13004b4659:
    contentColumnType: string
    fieldGroup: a6548a8e-edd2-4cbb-9200-db7de2726f75
    handle: pageBlockContent
    instructions: ''
    name: 'Page - Block Content'
    searchable: true
    settings:
      contentTable: '{{%matrixcontent_pageblockcontent}}'
      maxBlocks: ''
      minBlocks: ''
      propagationMethod: all
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
  d6471ab8-0d49-45bf-af5d-f0d2a860e267:
    contentColumnType: text
    fieldGroup: 2f26868b-418e-44a0-8e53-d367d9a163eb
    handle: metaSocialData
    instructions: ''
    name: 'Meta & Social Data'
    searchable: true
    settings:
      elementDisplayPreviewType: google
      facebookTabEnabled: ''
      generalEnabledFields:
        - seoPreview
        - seoTitle
        - seoDescription
        - seoImage
        - robots
        - canonicalUrl
      generalTabEnabled: '1'
      sitemapTabEnabled: ''
      twitterTabEnabled: ''
    translationKeyFormat: null
    translationMethod: none
    type: nystudio107\seomatic\fields\SeoSettings
globalSets:
  b59ae72a-8b0b-4bb9-83b9-a351b70b54a7:
    fieldLayouts:
      57d35cc6-d1f9-4d2a-8e1f-f4afe08c9e66:
        tabs:
          -
            fields:
              1b7a3230-f24a-4ac2-a997-3289e43ddf25:
                required: false
                sortOrder: 1
            name: Misc
            sortOrder: 1
    handle: site
    name: Site
matrixBlockTypes:
  4edb6c61-ee7b-4a62-ae07-d27f2127a80a:
    field: 90552b17-3ba7-452a-9dfd-0b13004b4659
    fieldLayouts:
      af512a4a-3b2f-4137-b331-1deeb26fa3cd:
        tabs:
          -
            fields:
              f64c5171-437f-45f4-ac5b-1164673e94f9:
                required: false
                sortOrder: 1
              feb39789-b26f-45a4-99fb-d7e4cc376989:
                required: false
                sortOrder: 2
            name: Content
            sortOrder: 1
    fields:
      f64c5171-437f-45f4-ac5b-1164673e94f9:
        contentColumnType: text
        fieldGroup: null
        handle: heading
        instructions: ''
        name: Heading
        searchable: true
        settings:
          byteLimit: null
          charLimit: null
          code: ''
          columnType: null
          initialRows: '4'
          multiline: ''
          placeholder: ''
        translationKeyFormat: null
        translationMethod: none
        type: craft\fields\PlainText
      feb39789-b26f-45a4-99fb-d7e4cc376989:
        contentColumnType: string
        fieldGroup: null
        handle: padding
        instructions: ''
        name: Padding
        searchable: true
        settings:
          optgroups: true
          options:
            -
              __assoc__:
                -
                  - label
                  - 'Top & Bottom'
                -
                  - value
                  - topBottom
                -
                  - default
                  - '1'
            -
              __assoc__:
                -
                  - label
                  - Top
                -
                  - value
                  - top
                -
                  - default
                  - ''
            -
              __assoc__:
                -
                  - label
                  - Bottom
                -
                  - value
                  - bottom
                -
                  - default
                  - ''
        translationKeyFormat: null
        translationMethod: none
        type: craft\fields\Dropdown
    handle: block
    name: Block
    sortOrder: 1
plugins:
  assetrev:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  blitz:
    edition: standard
    enabled: true
    schemaVersion: 3.6.6
  default-dashboard:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  freeform:
    edition: lite
    enabled: true
    schemaVersion: 3.0.7
  imager-x:
    edition: lite
    enabled: true
    schemaVersion: 3.0.0
  mailgun:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  retcon:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  retour:
    edition: standard
    enabled: true
    schemaVersion: 3.0.9
  seomatic:
    edition: standard
    enabled: true
    schemaVersion: 3.0.9
    settings:
      addHrefLang: true
      addPaginatedHreflang: true
      addXDefaultHrefLang: true
      cpTitlePrefix: '⚙ '
      devModeCpTitlePrefix: '&#x1f6a7;⚙ '
      devModeTitlePrefix: '&#x1f6a7; '
      displayAnalysisSidebar: true
      displayPreviewSidebar: true
      enableJsonLdEndpoint: ''
      enableMetaContainerEndpoint: ''
      environment: live
      generatorEnabled: true
      headersEnabled: true
      lowercaseCanonicalUrl: '1'
      maxDescriptionLength: 155
      maxTitleLength: 70
      metaCacheDuration: '604800'
      pluginName: SEO
      regenerateSitemapsAutomatically: true
      renderEnabled: true
      separatorChar: '|'
      sidebarDisplayPreviewTypes:
        - google
        - twitter
        - facebook
      siteGroupsSeparate: '1'
      siteUrlOverride: ''
      sitemapsEnabled: true
      socialMediaPreviewTarget: true
      submitSitemaps: true
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.2.1
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
sections:
  a4cade2e-b351-4d0b-8087-3328bc132811:
    enableVersioning: true
    entryTypes:
      0f92aa22-16d7-46d4-876a-135fba91d971:
        fieldLayouts:
          f5656723-1457-4216-a988-c5d52d84dbdf:
            tabs:
              -
                fields:
                  90552b17-3ba7-452a-9dfd-0b13004b4659:
                    required: false
                    sortOrder: 1
                name: General
                sortOrder: 1
              -
                fields:
                  d6471ab8-0d49-45bf-af5d-f0d2a860e267:
                    required: false
                    sortOrder: 1
                name: 'Meta & Social Data'
                sortOrder: 2
        handle: pageBlock
        hasTitleField: true
        name: 'Page - Block'
        sortOrder: 1
        titleFormat: ''
        titleLabel: Title
    handle: page
    name: Page
    previewTargets: null
    propagationMethod: all
    siteSettings:
      06fb793a-57ef-483e-8415-675d2cfa2fd8:
        enabledByDefault: true
        hasUrls: true
        template: _page/entry
        uriFormat: '{slug}'
    structure:
      maxLevels: null
      uid: 31b45cde-2559-489e-8cd0-3b3a8023dd15
    type: structure
siteGroups:
  a37b06c6-894d-4dad-a768-46c1a840e80b:
    name: 'Craft 3'
sites:
  06fb793a-57ef-483e-8415-675d2cfa2fd8:
    baseUrl: $SITE_URL
    handle: default
    hasUrls: true
    language: en-GB
    name: 'Craft 3'
    primary: true
    siteGroup: a37b06c6-894d-4dad-a768-46c1a840e80b
    sortOrder: 1
system:
  edition: pro
  live: true
  name: $SITE_NAME
  schemaVersion: 3.4.11
  timeZone: Europe/London
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: d22d8c4e-5130-4bb2-afad-a7c08be98605
  requireEmailVerification: true
volumes:
  0cf15aa5-fa7d-405e-9a99-aa30b099a53c:
    handle: files
    hasUrls: true
    name: Files
    settings:
      path: '@assetBasePath/files'
    sortOrder: 2
    type: craft\volumes\Local
    url: '@assetBaseUrl/files'
  d22d8c4e-5130-4bb2-afad-a7c08be98605:
    handle: images
    hasUrls: true
    name: Images
    settings:
      path: '@assetBasePath/images'
    sortOrder: 1
    type: craft\volumes\Local
    url: '@assetBaseUrl/images'
