dateModified: 1712693433
email:
  fromEmail: $CRAFT_EMAIL_SYSTEM
  fromName: $CRAFT_EMAIL_SYSTEM
  replyToEmail: null
  template: null
  transportSettings:
    command: '/usr/local/bin/mailpit sendmail -t --smtp-addr 127.0.0.1:1025'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    7b662bcd-ea91-4c91-86ce-c60348c664d1: Pages # Pages
    8b610edc-f2dd-46b6-9597-96fcbb6d302a: Simple # Simple
    08c386f4-5a41-4c9f-8282-f6785af06bfc: $CRAFT_SITE_NAME # $CRAFT_SITE_NAME
    19d6d897-1cde-4d59-914a-2bf8a23e7916: 'Public Schema' # Public Schema
    82622d73-a650-49b4-9dc7-86697b6b8560: 'Contact Form' # Contact Form
    bdf6317d-0df7-449f-a937-a1a274ffb106: 'Page - Blocks' # Page - Blocks
    d99bf7af-1eb1-4b77-814e-624eeec1a0e3: $CRAFT_SITE_NAME # $CRAFT_SITE_NAME
    eaf2a29e-5cf9-4770-9177-0bb0c1c973aa: New # New
plugins:
  blitz:
    edition: standard
    enabled: true
    schemaVersion: 5.0.0.4
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  formie:
    edition: standard
    enabled: true
    licenseKey: LZW7WQDYOIQSUYZ5Q8F8U6XQ
    schemaVersion: 3.4.2
  hyper:
    edition: standard
    enabled: true
    licenseKey: 3676GLSRO7YC75NEEL3CXV54
    schemaVersion: 1.0.0
  imager-x:
    edition: lite
    enabled: true
    licenseKey: LOFLTZOXPON235JMPY3H44MF
    schemaVersion: 4.0.0
  mailgun:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: AZ7WT9MFOZ3SCKHJT9RKY20J
    schemaVersion: 3.0.12
  servd-asset-storage:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  sprig:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: $CRAFT_SITE_NAME
  retryDuration: null
  schemaVersion: 5.0.0.20
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
