fieldLayouts:
  57d35cc6-d1f9-4d2a-8e1f-f4afe08c9e66:
    tabs:
      -
        elements:
          -
            fieldUid: 00cbe002-253f-4fca-b75f-ffc4cd309519 # Site - Header Navigation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Header
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 1b7a3230-f24a-4ac2-a997-3289e43ddf25 # Site - Cookie Consent
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Misc
        sortOrder: 2
handle: site
name: Site
